default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV['postgres_username'] %>
  password: <%= ENV['postgres_password'] %>
  
development:
  <<: *default
  database: NoSmoking_development

test:
  <<: *default
  database: NoSmoking_test

production:
  <<: *default
  database: NoSmoking_production
